services:
  app:
    container_name: stormy-dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./src/app:/stormy/src/app
      - ./public:/stormy/public
    restart: always
    ports:
      - '3000:3000'
