export const config = {
  PROD_API_URL: process.env.NEXT_PUBLIC_PROD_API_URL || '',
  STAGING_API_URL: process.env.NEXT_PUBLIC_STAGING_API_URL || '',
  API_KEY: process.env.NEXT_PUBLIC_API_KEY || '',
  COOKIE_NAME: process.env.NEXT_PUBLIC_COOKIE_NAME || '',
  COOKIE_EXPIRE: process.env.NEXT_PUBLIC_COOKIE_EXPIRE || '',
  STRIPE_PUBLIC_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY || '',
  STRIPE_SECRET_KEY: process.env.NEXT_PUBLIC_STRIPE_SECRET_KEY || '',
  CLOUDINARY_PUBLIC_KEY:
    process.env.NEXT_PUBLIC_CLOUDINARY_PUBLISHABLE_KEY || '',
  CLOUDINARY_SECRET_KEY: process.env.NEXT_PUBLIC_CLOUDINARY_SECRET_KEY || '',
  CLOUDINARY_NAME: process.env.NEXT_PUBLIC_CLOUDINARY_NAME || '',
  CLOUDINARY_UPLOAD_PRESET:
    process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET || '',
};
